# Generated by Django 4.2.6 on 2023-10-19 23:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PCPart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('CPU', 'CPU'), ('GPU', 'GPU')], max_length=3)),
                ('release_date', models.IntegerField(default=0)),
                ('core_clock', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('boost_clock', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('clock_unit', models.CharField(default='GHz', max_length=4)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TDP', models.IntegerField(default=0)),
                ('part_no', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
